# Change these first
owner: jonasled # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: URL Shorter
    url: https://jle.xyz
  - name: Website
    url: https://jonasled.de
  - name: Hastebin
    url: https://paste.jonasled.de
  - name: Nextcloud
    url: https://nextcloud.jonasled.de
  - name: Proxmox
    url: https://pve.jonasled.de
  - name: Matrix
    url: https://matrix.jonasled.de/_matrix/federation/v1/version
  - name: APT-Mirror
    url: https://apt.jonasled.de
  - name: Alpine-mirror
    url: https://alpine.jonasled.de
  - name: Gitlab
    url: https://gitlab.jonasled.de
  - name: Cyber Panel
    url: https://cp.jonasled.de
  - name: Mailcow
    url: https://mailcow.jonasled.de
  - name: Proxmox Mail Gateway
    url: https://pmg.jonasled.de
  - name: Proxmox Mail Gateway 2
    url: https://pmg2.jonasled.de:8006
  - name: Minio S3 Server
    url: https://s3.jonasled.de/share/
  - name: Gameserver Node
    url: https://1.game.jonasled.de:8444/
    expectedStatusCodes:
      - 401

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jonasled.de
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/jonasled/status/master/assets/logo.png
  name: Upptime
  introTitle: "**Jonas Leder Status**"
  introMessage: ""
  theme: night
  navbar:

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
